version: "3"
services:
  php:
    image: liaosp/php72
    volumes:
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - .:/app
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:rw #数据库配置
      - ${MYSQL_DATAPATH}:/var/lib/mysql #数据储存的地址
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
  redis:
    image: redis
