version: "3"
services:
  php:
    image: liaosp/php72
    volumes:
      - .:/app
  nginx:
    image: nginx
    ports:
      - 9091:80
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  redis:
    image: redis
